### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: William Michael Babij
# description: This will be meta HTML tag content. This can be ignored.
description: Personal website powered by Jekyll
# Set the URL to your custom domain
url: "https://wmbabij.dev"
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: William M Babij
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Technical Sales Engineer
# email: Your E-Mail address for the email button.
email: babij.wm@gmail.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: WilliamMBabij
codepen_username: William-Babij
dev_username: williammbabij
linkedin_username: william-babij-6814b333
twitter_username: WMBabij

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: About Me
# about_me_description: This will be displayed under the title.
about_me_description: I am a seasoned technology professional with a passion for helping people solve problems and learn new things. With over 12 years of experience as a Sales Engineer, I've developed a unique blend of technical expertise and customer-focused skills. My ability to quickly adapt to new software and technologies demonstrates my agility and commitment to continuous learning. I pride myself on my strong attention to detail, honed through my experience in technical support and quality assurance roles, which ensures that I deliver high-quality solutions to every challenge.<br><br>Throughout my career, I've built a reputation for excellence, with customers often reaching out to me directly for my problem-solving abilities. I take great pride in the positive feedback I receive from clients, which fuels my drive to continually improve and exceed expectations. My approach combines technical acumen with a genuine desire to educate and empower others, making me a valuable asset in any technology-driven environment. My experience spans various aspects of the tech industry, from network administration to customer support management, allowing me to bring a holistic perspective to my work. Whether I'm conducting product demonstrations, collaborating with R&D teams, or troubleshooting complex issues, my goal remains the same, to deliver exceptional results and ensure customer satisfaction.

# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: https://example.com/

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Projects
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: true
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: I am always excited to connect with fellow professionals, potential clients, and collaborators. Whether you have a question about my work, need assistance with a project, or are interested in discussing a potential opportunity, I would love to hear from you.<br><br>Feel free to reach out to me via email or connect with me on LinkedIn. I am open to exploring new opportunities and am always interested in engaging in meaningful conversations about technology, problem solving, and innovation.<br>Thank you for visiting my portfolio. I look forward to connecting with you soon!

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: williammbabij/neumorphism
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: "G-62E798WRL8"

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
